---
title: "Stat341 hw4"
output: html_document
---

```{r setup, include=TRUE}
library(fastR2) 

pvalues<-c(0.01,0.01,0.02,0.04,0.04,0.05,0.07,0.07,0.10, 
           0.19,0.24,0.27,0.34,0.37,0.44,0.50,0.53,0.54, 
           0.55,0.61,0.70,0.77,0.80,0.80,0.82,0.94,0.99)

gf_dhistogram(~pvalues) %>% 
  gf_dens(kernel="gaussian") %>%
  gf_labs(title="Gaussian kernel")

gf_dhistogram(~pvalues) %>% 
  gf_dens(kernel="rectangular") %>%
  gf_labs(title="Rectangular kernel")

gf_dhistogram(~pvalues) %>% 
  gf_dens(kernel="biweight") %>%
  gf_labs(title="Biweight kernel")

gf_dhistogram(~pvalues) %>% 
  gf_dens(kernel="cosine") %>%
  gf_labs(title="Cosine kernel")

gf_dhistogram(~pvalues) %>% 
  gf_dens(kernel="triangular") %>%
  gf_labs(title="Triangular kernel")

```
```{r setup, include=TRUE}
library(patchwork)
Plot_Data<-tibble(
x=c(-0.16, 1.17,-0.43,-0.02,1.06,-1.35,0.65,-1.12,0.03,-1.44), xk = sort(x),
pk = seq(0.05,0.95, by=0.1), #pk=(k-0.5)/(n)
qk = qnorm(pk)
) 
Plot_Data

ggplot(data=Plot_Data,mapping=aes(x=qk,y=xk))+ geom_point()

p1<-ggplot(data=Plot_Data,mapping=aes(sample=x))+ stat_qq() + stat_qq_line() + labs(title="Using stat_qq")
p2<-gf_qq(~x,data=Plot_Data, title("Using gf_qq")) %>% gf_qqline() 
p1+p2
```

```{r setup, include=TRUE}
Plot_Data<-tibble(pvalues=c(0.01,0.01,0.02,0.04,0.04,0.05,0.07,0.07,0.10,
                            0.19,0.24,0.27,0.34,0.37,0.44,0.50,0.53,0.54, 
                            0.55,0.61,0.70,0.77,0.80,0.80,0.82,0.94,0.99), 
                  xk = sort(pvalues),
                  pk = c(0.5/27, 1.5/27, 2.5/27, 3.5/27, 4.5/27, 5.5/27, 6.5/27, 7.5/27, 8.5/27, 9.5/27,
                           10.5/27, 11.5/27, 12.5/27, 13.5/27, 14.5/27, 15.5/27, 16.5/27, 17.5/27, 18.5/27, 
                           19.5/27, 20.5/27, 21.5/27, 22.5/27, 23.5/27, 24.5/27, 25.5/27, 26.5/27),
                  qk = qnorm(pk)) 
Plot_Data

ggplot(data=Plot_Data,mapping=aes(x=qk,y=xk))+ geom_point()
p1<-ggplot(data=Plot_Data,mapping=aes(sample=pvalues))+ stat_qq() + stat_qq_line() + labs(title="Using stat_qq")
p2<-gf_qq(~pvalues,data=Plot_Data, title("Using gf_qq")) %>% gf_qqline() 
p1+p2

```


